center: asia
daylightimagefilename: P:\tmp\day.png
interval: 8
last_run: "2019-09-22 19:09:07"
nighttimeimagefilename: P:\tmp\night.png
outputimagefilename: P:\tmp\slmbg2.png
type: static
width: 1920
